compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
